#!/bin/sh

# this is a wrapper script for dhclient-script, which is called by OpenBSD's dhclient
# when a DHCP event occurs. It calls dhclient-script and then follows up with
# maintenance tasks to manage an IPv6 tunnel (from tunnelbroker.net).

# the following variables must be defined in the configuration file
#HE_USERID
#HE_TUNNELID
#HE_MD5PASS
#TUNNEL_IF
#TUNNEL_SRV_IPV4
#TUNNEL_SRV_IPV6
#TUNNEL_LOCAL_IPV6

LOGGER="/user/bin/logger"
WGET="/usr/local/bin/wget"
IFCONFIG="/sbin/ifconfig"

DHCLIENT_SCRIPT="/etc/dhclient-script"

CONF="/etc/defaults/dhclient-script-ipv6tunnel.conf"

# load configuration file
. ${CONF}

# call normal dhclient-script, if dhclient-script fails, follow suit
if ! ${DHCLIENT_SCRIPT}; then exit 1; fi

# manage IPv6 tunnel
case $reason in

BOUND|RENEW|REBIND|REBOOT)

    $LOGGER "Configuring IPv6 tunnel following DHCP ${reason}"

    # if new IP address, update tunnel service
    if [ "$old_ip_address" != "$new_ip_address" ]; then

       $LOGGER "Updating tunnelbroker.net with changed IPv4 address (${old_ip_address} => ${new_ip_address})"
       $WGET --no-check-certificate \
             "https://ipv4.tunnelbroker.net/ipv4_end.php?ip=AUTO&pass=${HE_MD5PASS}&apikey=${HE_USERID}&tid=${HE_TUNNELID}"
    fi

    # setup tunnel (IPv4 end points)
    $IFCONFIG ${TUNNEL_IF} tunnel ${new_ip_address} ${TUNNEL_SRV_IPV4}

    # setup tunnel (IPv6 end points)
    $IFCONFIG ${TUNNEL_IF} inet6 alias ${TUNNEL_LOCAL_IPV6} ${TUNNEL_SRV_IPV6} prefixlen 128

    # setup IPv6 default route
    route -n add -inet6 default ${TUNNEL_SRV_IPV6}

    $LOGGER "Done configuring IPv6 tunnel."

    ;;
esac

exit 0
